name: RoadChoice Search Connector - Blog Upsert

on:
  repository_dispatch:
    types:
      - resource-published
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Site: ${{ github.event.client_payload.site }}"
          echo "Org: ${{ github.event.client_payload.org }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  notify-connector:
    if: >
      (github.event.client_payload.status == 200 || github.event.client_payload.status == 204)
      && endsWith(github.event.client_payload.path, '.md')
      && (
        startsWith(github.event.client_payload.path, '/blog/')
      )
    runs-on: ubuntu-latest
    env:
      EDS_CONNECTOR_DOMAIN: ${{ vars.EDS_CONNECTOR_DOMAIN }}
      EDS_API_KEY: ${{ secrets.EDS_API_KEY }}
    outputs:
      http_code: ${{ steps.notify.outputs.http_code }}
      body: ${{ steps.notify.outputs.body }}
      page_path: ${{ steps.notify.outputs.page_path }}
    steps:
      - name: Notify upsert endpoint
        id: notify
        shell: bash
        run: |
          # Give time for publish pipeline to finish
          sleep 45s

          RAW_PATH="${{ github.event.client_payload.path }}"

          # Strip "index.md" or just ".md"
          if [[ "$RAW_PATH" == *"index.md" ]]; then
            PAGE_PATH="${RAW_PATH%"index.md"}"
          else
            PAGE_PATH="${RAW_PATH%.md}"
          fi

          WEBSITE_NAME="${{ github.event.client_payload.site }}"
          URI="${EDS_CONNECTOR_DOMAIN}/$WEBSITE_NAME"

          echo "Original path: $RAW_PATH"
          echo "Final upsert path: $PAGE_PATH"
          echo "Posting to: $URI"

          BODY='{ "paths": [ "'$PAGE_PATH'" ] }'
          BODY="$(echo "$BODY" | jq -c)"

          # Call API and capture both body and HTTP status code
          response=$(curl -s -w "%{http_code}" -o response_body.txt -H "x-api-key: $EDS_API_KEY" -X POST "$URI" -d "$BODY")
          http_code="${response: -3}"
          body=$(cat response_body.txt)

          echo "HTTP status: $http_code"
          echo "Response body: $body"

          # Expose for downstream job
          echo "http_code=$http_code" >> $GITHUB_OUTPUT
          printf "body<<EOF\n%s\nEOF\n" "$body" >> $GITHUB_OUTPUT
          echo "page_path=$PAGE_PATH" >> $GITHUB_OUTPUT

          # Fail job on non-2xx so the status-checker can alert
          if [[ ! "$http_code" =~ ^2[0-9][0-9]$ ]]; then
            echo "API call failed with status $http_code"
            exit 1
          fi

  status-checker:
    needs: notify-connector
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      BODY: ${{ needs.notify-connector.outputs.body }}
      HTTP_CODE: ${{ needs.notify-connector.outputs.http_code }}
    steps:
      - name: Notify on specific connector failures in Slack
        if: ${{ needs.notify-connector.result != 'success' }}
        shell: bash
        run: |
          path="${{ needs.notify-connector.outputs.page_path }}"
          site="${{ github.event.client_payload.site }}"
          repo="${{ github.repository }}"
          run_url="https://github.com/${repo}/actions/runs/${{ github.run_id }}"
          body="$BODY"
          http_code="$HTTP_CODE"
          actor="${{ github.actor }}"
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Errors to alert on
          declare -a errors=(
            "No Valid Documents to Ingest"
            "Documents not ingested"
            "Internal Server Error"
            "Document not found in OpenSearch"
          )

          send_message=false
          reason="Unknown error"

          for err in "${errors[@]}"; do
            if [[ "$body" == *"$err"* ]]; then
              reason="$err"
              send_message=true
              break
            fi
          done

          if [ "$send_message" = true ]; then
            payload="{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \":x: *Search Connector FAILED: $reason*\n*Site:* $site\n*Path:* \`$path\`\n*HTTP Status:* $http_code\n*Triggered by:* $actor\n*Time (UTC):* $timestamp\n<${run_url}|View Workflow Run>\"
                  }
                }
              ]
            }"
            curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
          else
            echo "No matching error, no Slack notification sent."
          fi

      - name: Connector job succeeded or no Slack notification required
        if: ${{ needs.notify-connector.result == 'success' }}
        run: |
          echo "Notify connector job succeeded. No Slack notification sent."
          echo "Cleaned path used for upsert: ${{ needs.notify-connector.outputs.page_path }}"
          echo "Original path from event: ${{ github.event.client_payload.path }}"
          echo "Status: ${{ needs.notify-connector.result }}"